#!/bin/bash

LC_ALL=C
TOTAL_POINTS=0
mkdir -p out

check_one() {
	./paranthesinator < in/$1.in > out/$1.out
	if cmp --silent -- out/$1.out ref/$1.ref; then
		printf "Test %02d ................. PASSED: 2.0p\n" $1
		TOTAL_POINTS=$(($TOTAL_POINTS + 2))
	else
		printf "Test %02d ................. FAILED: 0.0p\n" $1
	fi
}

echo "---------------TASK 1---------------"
for i in $(seq 1 15); do
	check_one $i
done
printf "\nTASK 1 SCORE: %.2f / 30.00\n\n" $TOTAL_POINTS
